### ISSUE TITLE
UTM not being stored when in production at aws

### ISSUE THREAD

**Issue by ttakamoto** [kyranb/Footprints#11]
Hi Kyranb, 

I installed correctly the Footprints in my 5.4 laravel project and it worked well in my local environment using valet. But when running in production(AWS - Elastic Beanstalk) the table visits don't record a single visit with utm_* attribute, even if I force it in the URI.

Did you have any problem regarding this environment or any other during your development?

**Comment by kyranb** [comment]
I'm personally not running on ELB/EC2 so I can't comment on why it won't work in production.

Is your web server passing along all other UTM parameters to your application server?
