### ISSUE TITLE
UTM POST issue

### ISSUE THREAD

**Issue by xakzona** [kyranb/Footprints#14]
Can you add config parameter where can be set HTTP methods? Because now it use only GET method

**Comment by kyranb** [comment]
What would your use case for tracking POST requests be?

**Comment by xakzona** [comment]
We have a landing with client data  form, that POST data to our website with UTM attributes.
Thank you for your time

**Comment by kyranb** [comment]
This package is for tracking landing page visits rather than every HTTP request.

If a user is redirected to a page after submitting the form, that should still be able to hook in and capture the attribution data?
