### ISSUE TITLE
Laravel 5.4 error

### ISSUE THREAD

**Issue by jbardnz** [kyranb/Footprints#16]
Hey,

I have just upgraded to Laravel 5.4 and seem to be getting an issue. The error is **Closure object cannot have properties**. The issue seems to be related to asyncTrackVisit in CaptureAttributionDataMiddleware.

Anyone else seen this or knows how to fix it?

**Comment by jbardnz** [comment]
Just to add to this, if you switch async off in your config that also gives you a different error:

`Column not found: 1054 Unknown column 'landing_params' in 'field list' `

**Comment by iredmedia** [comment]
I'm on 5.4 and not experiencing this issues. Perhaps you didn't run the migration?

**Comment by roboticsexpert** [comment]
i have clouse object issue too

**Comment by marcroberts** [comment]
Strangely I was **not** getting this error with 5.4 through to 5.7 but on upgrading to 5.8 (and testing 6.x) I was getting this ‽

I've open https://github.com/kyranb/Footprints/pull/23 to resolve this
