### ISSUE TITLE
using this in a RESTful project

### ISSUE THREAD

**Issue by MostafaNobaghi** [kyranb/Footprints#19]
how can i use this package in a RESTful project, (Models are in API  and web site connect to database via API)

**Comment by kevnk** [comment]
I have the same question

**Comment by kyranb** [comment]
Me too! Does anyone out there have any ideas on how to go about this?

I'm guessing you would need to pass through some other way to identify each unregistered user rather than the `cookieToken`.

**Comment by bilfeldt** [comment]
> I'm guessing you would need to pass through some other way to identify each unregistered user rather than the `cookieToken`.

You are correct. API are stateless by defination so you do not have access to cookies. Best idea is using "browser" (client) fingerprints - have a look at: https://coveryourtracks.eff.org/

**Comment by bilfeldt** [comment]
another option could be to rely solely on IP address or in combination with relevant headers like `User-agent` for example. This should would be possible with #36

**Comment by kyranb** [comment]
Closing this for now, unless it's worthwhile having a 'fingerprint()' method that hashes the ip and headers?

**Comment by bilfeldt** [comment]
> Closing this for now, unless it's worthwhile having a 'fingerprint()' method that hashes the ip and headers?

@kyranb That is a brilliant idea! Maybe adding a request macro for `fingerprint()` which uses an interface that the can be changed by the developer to implement any logic desired? The default would use cookie if set and alternative a hash of ip and user agent? Should I make a PR?
