### ISSUE TITLE
Scheduled deletion of old unclaimed Visits

### ISSUE THREAD

**Issue by ralphmorris** [kyranb/Footprints#24]
Hey,

This package looks great!

Quick question, I noticed the attribution_duration config. Does this just amend how long the config is stored? Is there any built in way of deleting old Visit rows that weren't claimed by a user_id?

I know it can easily be done as a scheduled artisan command in Laravel but just wondering if there was any consideration to this/anything built in?

Thanks :)

**Comment by kyranb** [comment]
Hey Ralph!

Thanks, glad you like it :)

The `attribution_duration` config essentially sets the attribution window for how long a visit will count as being attributed for a user registration.

At this stage, the package doesn't handle deleting the visit rows.

I'd happily welcome a PR to (optionally) support deleting old records though. Some folks find it useful to keep track of all visits prior to a registration to see the path/journey someone took before signing up.
