### ISSUE TITLE
INSTALLATION FAILS

### ISSUE THREAD

**Issue by srhtylmz19** [kyranb/Footprints#26]
- Installation request for laravel/framework (locked at v7.2.2, required as ^7.0) -> satisfiable by laravel/framework[v7.2.2].

when i try to 'composer require kyranb/footprints' i got this error

**Comment by kyranb** [comment]
YOUR CAPS LOCK IS STUCK ;)

Fixed with this: https://github.com/kyranb/Footprints/pull/27
