### ISSUE TITLE
Logging user IP and much more

### ISSUE THREAD

**Issue by bilfeldt** [kyranb/Footprints#35]
@kyranb would you be willing to consider a PR implementing implementing what is described below?

## Description
Currently there is a concept of "Custom Parameters" (defined in the configuration: `footprints.custom_parameters`) which should make it possible to log extra stuff that might be relevant. However we are limited to [request inputs](https://laravel.com/docs/8.x/requests#retrieving-an-input-value) since this is implemented like so:

```php
// https://github.com/kyranb/Footprints/blob/master/src/Middleware/CaptureAttributionDataMiddleware.php
    /**
     * @return array
     */
    protected function getCustomParameter()
    {
        $arr = [];

        if (config('footprints.custom_parameters')) {
            foreach (config('footprints.custom_parameters') as $parameter) {
                $arr[$parameter] = $this->request->input($parameter); // <--- Only inputs
            }
        }

        return $arr;
    }
```

### Cons
Now we all know that cookies are not always the best way to track users. In many applications where it was not possible to track a cookie then I assume that it would be sufficient to match previous visits based on the IP address of the user (for many applications you will never see multiple users from the same IP address) or slightly better would be a combination of IP address and the `User-agent` provided in the headers. Now none of these approaches are possible using the package right now.

## Suggestion
These suggestions would each constitute a breaking change, so I am proposing that all of them are implemented in the same go:

### Adding IP
I suggest adding the IP of the request ([`$request->ip()`](https://laravel.com/api/8.x/Illuminate/Http/Request.html#method_ip)) in [`CaptureAttributionDataMiddleware`](https://github.com/kyranb/Footprints/blob/master/src/Middleware/CaptureAttributionDataMiddleware.php) since this is simple and could be used for matching in many cases. This would also need to be added to the Visit model and to the migration.

Note that I am **not** proposing to save the headers as described as an option in the initial description.

### Introducing CaptureHandler
I suggest modifying the `CaptureAttributionDataMiddleware` so that everything except the `handle` method is moved to a separate class called `CaptureHandler` which implements a new interface called `CaptureHandlerInterface`.

The point being that a developer can easily swap out the Handler for another concrete implementation and hence save the request in _any way or shape_ they find useful. This would also solve #21.

### Moving authenticated user
Since we are already introducing breaking changes then I suggest moving the [TrackVisit.php#L26](https://github.com/kyranb/Footprints/blob/47bc103342246369fb9cbede59d618938c7218b8/src/Jobs/TrackVisit.php#L26):

```php
    public function handle()
    {
        $user = [];
        $user[config('footprints.column_name')] = Auth::user() ? Auth::user()->id : null; // <-- Moving to CaptureHandler enable modifications

        $visit = Visit::create(array_merge([
        ....
```

to the new `CaptureHandler` (previously [CaptureAttributionDataMiddleware.php#L106](https://github.com/kyranb/Footprints/blob/47bc103342246369fb9cbede59d618938c7218b8/src/Middleware/CaptureAttributionDataMiddleware.php#L106):

which would partially solve #30

**Comment by kyranb** [comment]
Hi there,

Thanks so much for this proposal. I love the added flexibility it would bring. Happy to accept a PR :)

If the new `CaptureHandler` captures an IP address, perhaps add a configuration option so that is disabled by default. I think logging IP addresses should be opt-in rather than opt-out.

**Comment by bilfeldt** [comment]
Glad to hear @kyranb 👍 

I am thinking about splitting this into a few PRs that you can review individually - let me know if you think otherwise:

- [x] Implement new interfaces - PR #36 - note I am using another (and hopefully better) name convention that my original post here
- [ ] Implement logging of IP (default should be false)
- [ ] Implement `TrackableInterface`
  - Implement this interface in the `TrackRegistrationAttribution` trait
  - Use the new interface instead of the id as input parameter to the jobs (should solve #21 and #30)

**Comment by bilfeldt** [comment]
Issue closed - See PR implementations in comment above
