### ISSUE TITLE
Packagist auto update disabled

### ISSUE THREAD

**Issue by bilfeldt** [kyranb/Footprints#44]
@kyranb Wanted to let you know that I just refreshed [this package on Packagist](https://packagist.org/packages/kyranb/footprints) because it does not auto-updates. This can be enabled using this guide: https://packagist.org/about#how-to-update-packages

<img width="1162" alt="Screenshot 2021-02-16 at 14 13 38" src="https://user-images.githubusercontent.com/30228807/108067828-9b9f9e80-7061-11eb-9be0-68e204435bfc.png">

**Comment by kyranb** [comment]
Done!
