### ISSUE TITLE
Manually Creating a User Fails

### ISSUE THREAD

**Issue by spinalwiz** [kyranb/Footprints#51]
Hi,

I think there might be an issue when manually creating a User through Eloquent (e.g. `User::create($data)`).  In `TrackRegistrationAttribution.php`  there is this boot method:

```php
 public static function bootTrackRegistrationAttribution()
    {
        // Add an observer that upon registration will automatically sync up prior visits.
        static::created(function (Model $model) {
            $model->trackRegistration();
        });
    }
```
    
Which calls this:
    
```php
    /**
     * Assign earlier visits using current request.
     */
    public function trackRegistration(Request $request): void
    {
        $job = new AssignPreviousVisits($request->footprint(), $this);

        if (config('footprints.async') == true) {
            dispatch($job);
        } else {
            $job->handle();
        }
    }
```
    
But there is no Request so it fails with error: 
    
 ` Too few arguments to function App\Models\User::trackRegistration(), 0 passed`

**Comment by kyranb** [comment]
Nice find!

What behaviour would you expect when creating a model manually? 

@bilfeldt Any ideas? 

Perhaps rather than retrieving `Request` by typehinting we could use the `resolve` helper? https://laravel.com/docs/master/helpers#method-resolve

**Comment by bilfeldt** [comment]
@spinalwiz good catch.

We definitely need a test for this :(

@kyranb I think it might be easier to simply use the [`request` helper](https://laravel.com/docs/master/helpers#method-request). This could be added either in `bootTrackRegistrationAttribution` like so:

```php
 public static function bootTrackRegistrationAttribution()
    {
        // Add an observer that upon registration will automatically sync up prior visits.
        static::created(function (Model $model) {
            $model->trackRegistration(request());
        });
    }
```
which would NOT be a breaking change but just a fix.

Or we could remove it as an input in `trackRegistration` which would be a breaking change:

```php
    /**
     * Assign earlier visits using current request.
     */
    public function trackRegistration(): void
    {
        $job = new AssignPreviousVisits(request()->footprint(), $this);

        if (config('footprints.async') == true) {
            dispatch($job);
        } else {
            $job->handle();
        }
    }
```

The latter approach might make it easier to customise the behaviour (one can simply override the `trackRegistration` method.) but on the other hand it kind of "hides" the dependency of the request object. I personally would prefer the first approach.

**Comment by julienarcin** [comment]
I had the same problems for testing purposes.

I created a PR #52 with @bilfeldt first solution (which seems to be the easiest).
