### ISSUE TITLE
Exclude robots

### ISSUE THREAD

**Issue by tainmar** [kyranb/Footprints#54]
Hi there ! Great package, thank you very much for this.
Just wondering if robots were excluded from footprints or not ?
I fell like it is not the case.
Thank you

**Comment by tainmar** [comment]
Or am I missing something ?
I can make a PR if you feel this would be useful

**Comment by kyranb** [comment]
You're more than welcome :)

Currently there is no filtering that takes place there, so yes a PR for some kind of extensible filter with a sane default would make sense :)
