### ISSUE TITLE
Problem identifying users when queued

### ISSUE THREAD

**Issue by julienarcin** [kyranb/Footprints#60]
Hello !

There is a bug in the src/Jobs/TrackVisit.php file.

`
Visit::create(array_merge([
    config('footprints.column_name') => Auth::user() ? Auth::user()->id : null,
], $this->attributionData));
`

A queued job should not make a call to the Auth::user function (since it won't be available in async mode).

The Auth::user() should be passed when dispatching the job.

I made a PR here #59

**Comment by kyranb** [comment]
Thanks ☺️
