### ISSUE TITLE
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'referrer_url'

### ISSUE THREAD

**Issue by bilfeldt** [kyranb/Footprints#63]
This SQL error

```sql
PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'referrer_url' at row 1
  File "/public/index.php", line 52
    $request = Request::capture()
...
(64 additional frame(s) were not displayed)
```

occurs when the `referrer_url` is too long for the database column which is per default set in the migration to `string('field')` which creates a `varchar(255)`.

This is causing problems for us for some email client where the referrer is a **really** long string with some unique ids auto generated.

Basically there are two options:
1. Change the default migration to some longer strings
2. Add truncation before storing to the database

I personally lean towards truncating the fields since these long url's will not provided any useful data.

**Comment by kyranb** [comment]
Thanks so
