### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by gyurobenjamin** [kyranb/Footprints#8]
Here is my `composer require kyranb/footprints` result:

Using version ^0.2.4@beta for kyranb/footprints
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for kyranb/footprints ^0.2.4@beta -> satisfiable by kyranb/footprints[0.2.4-beta].
    - Conclusion: remove laravel/framework v5.1.45
    - Conclusion: don't install laravel/framework v5.1.45
    - kyranb/footprints 0.2.4-beta requires illuminate/support ~5.3 -> satisfiable by illuminate/support[5.3.x-dev, 5.4.x-dev, v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - don't install illuminate/support 5.3.x-dev|don't install laravel/framework v5.1.45
    - don't install illuminate/support v5.3.0|don't install laravel/framework v5.1.45
    - don't install illuminate/support v5.3.16|don't install laravel/framework v5.1.45
    - don't install illuminate/support v5.3.23|don't install laravel/framework v5.1.45
    - don't install illuminate/support v5.3.4|don't install laravel/framework v5.1.45
    - don't install illuminate/support 5.4.x-dev|don't install laravel/framework v5.1.45
    - Installation request for laravel/framework (locked at v5.1.45, required as 5.1.*) -> satisfiable by laravel/framework[v5.1.45].

Installation failed, reverting ./composer.json to its original content.

and here is my installed packages:

`anhskohbo/no-captcha                  2.1.2              No CAPTCHA reCAPTCHA For Laravel.
barryvdh/laravel-debugbar             v2.3.0             PHP Debugbar integration for Laravel
bosnadev/repositories                 0.12               Laravel Repositories
classpreloader/classpreloader         3.0.0              Helps class loading performance by generating a single PHP file containing all of the autoloaded files for a specific use case
danielstjules/stringy                 1.10.0             A string manipulation library with multibyte support
dnoegel/php-xdg-base-dir              0.1                implementation of xdg base directory specification for php
doctrine/annotations                  v1.3.0             Docblock Annotations Parser
doctrine/cache                        v1.6.1             Caching library offering an object-oriented API for many cache backends
doctrine/collections                  v1.3.0             Collections Abstraction library
doctrine/common                       v2.6.1             Common Library for Doctrine projects
doctrine/dbal                         v2.5.5             Database Abstraction Layer
doctrine/inflector                    v1.1.0             Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                 1.0.5              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                        v1.0.1             Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
fzaninotto/faker                      v1.6.0             Faker is a PHP library that generates fake data for you.
guzzlehttp/guzzle                     6.2.2              Guzzle is a PHP HTTP client library
guzzlehttp/promises                   1.2.0              Guzzle promises library
guzzlehttp/psr7                       1.3.1              PSR-7 message implementation
hamcrest/hamcrest-php                 v1.2.2             This is the PHP port of Hamcrest Matchers
intervention/image                    2.3.8              Image handling and manipulation library with support for Laravel integration
jakub-onderka/php-console-color       0.1                
jakub-onderka/php-console-highlighter v0.3.2             
jeremeamia/SuperClosure               2.2.0              Serialize Closure objects, including their context and binding
laravel/framework                     v5.1.45            The Laravel Framework.
laravel/socialite                     dev-master 2979451 Laravel wrapper around OAuth 1 & OAuth 2 libraries.
laravelcollective/html                v5.1.9             
league/flysystem                      1.0.32             Filesystem abstraction: Many filesystems, one API.
league/oauth1-client                  1.7.0              OAuth 1.0 Client Library
maximebf/debugbar                     v1.13.0            Debug bar in the browser for php application
mockery/mockery                       0.9.5              Mockery is a simple yet flexible PHP mock object framework for use in unit testing with PHPUnit, PHPSpec or any other testing framework. Its core goal is to offer a test double framework with a ...
monolog/monolog                       1.21.0             Sends your logs to files, sockets, inboxes, databases and various web services
mtdowling/cron-expression             v1.1.0             CRON for PHP: Calculate the next or previous run date and determine if a CRON expression is due
nesbot/carbon                         1.21.0             A simple API extension for DateTime.
nikic/php-parser                      v2.1.1             A PHP parser written in PHP
paragonie/random_compat               v1.4.1             PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phpdocumentor/reflection-common       1.0                Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock     3.1.1              With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver           0.2                
phpspec/php-diff                      v1.0.2             A comprehensive library for generating differences between two hashable objects (strings or arrays).
phpspec/phpspec                       2.5.3              Specification-oriented BDD framework for PHP 5.3+
phpspec/prophecy                      v1.6.1             Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage             2.2.4              Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator             1.4.1              FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template             1.2.1              Simple template engine.
phpunit/php-timer                     1.0.8              Utility class for timing
phpunit/php-token-stream              1.4.8              Wrapper around PHP's tokenizer extension.
phpunit/phpunit                       4.8.27             The PHP Unit Testing framework.
phpunit/phpunit-mock-objects          2.3.8              Mock Object library for PHPUnit
predis/predis                         v1.1.1             Flexible and feature-complete Redis client for PHP and HHVM
psr/http-message                      1.0.1              Common interface for HTTP messages
psr/log                               1.0.2              Common interface for logging libraries
psy/psysh                             v0.7.2             An interactive shell for modern PHP.
sebastian/comparator                  1.2.0              Provides the functionality to compare PHP values for equality
sebastian/diff                        1.4.1              Diff implementation
sebastian/environment                 1.3.8              Provides functionality to handle HHVM/PHP environments
sebastian/exporter                    1.2.2              Provides the functionality to export PHP variables for visualization
sebastian/global-state                1.1.1              Snapshotting of global state
sebastian/recursion-context           1.0.2              Provides functionality to recursively process PHP variables
sebastian/version                     1.0.6              Library that helps with managing the version number of Git-hosted PHP projects
segmentio/analytics-php               dev-master 2025040 Segment Analytics PHP Library
swiftmailer/swiftmailer               v5.4.3             Swiftmailer, free feature-rich PHP mailer
symfony/console                       v2.7.20            Symfony Console Component
symfony/css-selector                  v2.8.13            Symfony CssSelector Component
symfony/debug                         v2.7.20            Symfony Debug Component
symfony/dom-crawler                   v2.7.20            Symfony DomCrawler Component
symfony/event-dispatcher              v2.8.13            Symfony EventDispatcher Component
symfony/finder                        v2.7.20            Symfony Finder Component
symfony/http-foundation               v2.7.20            Symfony HttpFoundation Component
symfony/http-kernel                   v2.7.20            Symfony HttpKernel Component
symfony/polyfill-mbstring             v1.2.0             Symfony polyfill for the Mbstring extension
symfony/polyfill-php56                v1.2.0             Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-util                 v1.2.0             Symfony utilities for portability of PHP codes
symfony/process                       v2.7.20            Symfony Process Component
symfony/routing                       v2.7.20            Symfony Routing Component
symfony/translation                   v2.7.20            Symfony Translation Component
symfony/var-dumper                    v2.7.20            Symfony mechanism for exploring and dumping PHP variables
symfony/yaml                          v3.1.6             Symfony Yaml Component
vlucas/phpdotenv                      v1.1.1             Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.
webmozart/assert                      1.1.0              Assertions to validate method input/output with nice error messages.
`

I've tried to remove all packages and reinstall etc.. still same. Do you have any idea what can be wrong?

**Comment by gyurobenjamin** [comment]
I only can install the 0.2.3-beta

**Comment by kyranb** [comment]
Just made a change to the composer dependency requirements which should resolve this:
0.2.5-beta
